### ISSUE TITLE
MYMETA should not be included

### ISSUE THREAD

**Issue by chorny** [ribugent/perl-apache-tika#1]
Your distribution (RIBUGENT/Apache-Tika-0.04.tar.gz) contains files MYMETA.yml and/or MYMETA.json. These files should not be included into distribution - they are generated when installing.
See http://weblog.bulknews.net/post/44251476706/stop-shipping-mymeta-to-cpan

P.S. If this report is about old version, please delete old indexed versions mentioned here: http://cpanold.chorny.net/?a=RIBUGENT and contact me.

**Comment by ribugent** [comment]
Thanks for the info, I'll fix asap

**Comment by chorny** [comment]
Same for file "Makefile".

**Comment by ribugent** [comment]
Released 0.06 version which avoids adding Makefile and includes a more complete MANIFEST.SKIP

The old releases has just been scheduled for deletion.
